export { default as Home } from './Homapage/Home'
export { default as UserList } from './UserList/UserList'
export { default as User } from './User/User'
export { default as NewUser } from './NewUser/NewUser'
export { default as ProductList } from './ProductList/ProductList'
export { default as Product } from './Product/Product'
export { default as NewProduct } from './NewProduct/NewProduct'
